//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHBank
    {
        public int ACHBankId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> RoutingNumber { get; set; }
        public Nullable<decimal> AccountNumber { get; set; }
        public string Descrption { get; set; }
        public string RemittanceNotes { get; set; }
    
        public virtual TypeList TypeList { get; set; }
    }
}
