//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APBill
    {
        public int APBillId { get; set; }
        public Nullable<int> MasterTrxId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public Nullable<int> BillMonth { get; set; }
        public Nullable<int> BillYear { get; set; }
        public Nullable<int> CheckTypeListId { get; set; }
        public Nullable<int> FranchiseeReportId { get; set; }
        public Nullable<int> ManualCheckId { get; set; }
        public Nullable<int> TransactionStatusListId { get; set; }
        public string TransactionNumber { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> FranchiseeTurnaroundCheckId { get; set; }
        public Nullable<decimal> CheckAmount { get; set; }
        public Nullable<int> PayTypeListId { get; set; }
        public Nullable<int> ImpId { get; set; }
        public Nullable<int> CheckBookTransactionTypeListId { get; set; }
        public Nullable<int> CheckBookTransactionListId { get; set; }
        public Nullable<int> FranchiseeReportFinalizedId { get; set; }
        public Nullable<int> SourceTypeListId { get; set; }
        public Nullable<int> SourceId { get; set; }
    
        public virtual MasterTrx MasterTrx { get; set; }
    }
}
