//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuthMenu()
        {
            this.AuthRoleAccesses = new HashSet<AuthRoleAccess>();
        }
    
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public string MenuUrl { get; set; }
        public Nullable<int> MenuLevel { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public Nullable<int> ParentMenuId { get; set; }
        public string PageName { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
        public string MenuImageUrl { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthRoleAccess> AuthRoleAccesses { get; set; }
    }
}
