//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthRoleAccess
    {
        public int RoleAccessId { get; set; }
        public int RoleId { get; set; }
        public int MenuId { get; set; }
        public Nullable<bool> IsDeleteAccess { get; set; }
        public Nullable<bool> IsInsertAccess { get; set; }
        public Nullable<bool> IsViewAccess { get; set; }
        public Nullable<int> RegionId { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual AuthMenu AuthMenu { get; set; }
        public virtual AuthRole AuthRole { get; set; }
    }
}
