//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public int BatchId { get; set; }
        public Nullable<long> BatchNumber { get; set; }
        public Nullable<int> BatchTypeListId { get; set; }
        public Nullable<int> InvoiceCount { get; set; }
        public Nullable<decimal> InvoiceTotalAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> MasterTrxTypeListId { get; set; }
        public Nullable<int> NumberofCount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual BatchTypeList BatchTypeList { get; set; }
    }
}
