//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        public int BonusId { get; set; }
        public Nullable<int> SalesUserId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> BonusAmount { get; set; }
        public string Explanation { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<System.DateTime> BonusDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsAdditionalBonus { get; set; }
        public Nullable<int> CommissionScheduleId { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
