//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckBookTransactionTypeList
    {
        public int CheckBookTransactionTypeListId { get; set; }
        public string Name { get; set; }
        public string DisplayType { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public Nullable<bool> IsSystemGenerated { get; set; }
        public Nullable<int> CheckBookAmountTypeListId { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public string Code { get; set; }
        public Nullable<int> MasterTrxTypeListId { get; set; }
        public Nullable<int> ServiceTypeListId { get; set; }
        public Nullable<bool> Deposit { get; set; }
        public Nullable<bool> Payment { get; set; }
        public Nullable<int> CheckTemplateId { get; set; }
    }
}
