//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckBook
    {
        public int CheckBookId { get; set; }
        public Nullable<int> FundTypeListId { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public string PeriodId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> BillMonth { get; set; }
        public Nullable<int> BillYear { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> SourceTypeListId { get; set; }
        public Nullable<int> TransactionStatusListId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<bool> Reconciled { get; set; }
        public string Memo { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CheckBookTransactionTypeListId { get; set; }
        public Nullable<int> CheckBookAmountTypeListId { get; set; }
        public string Code { get; set; }
        public Nullable<int> ServiceTypeListId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> MasterTrxTypeListId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> ImpId { get; set; }
        public Nullable<int> MasterTrxId { get; set; }
        public Nullable<int> ReconciledBy { get; set; }
        public Nullable<System.DateTime> ReconciledDate { get; set; }
        public Nullable<int> LedgerAcctId { get; set; }
        public Nullable<int> LedgerSubAcctId { get; set; }
    
        public virtual MasterTrx MasterTrx { get; set; }
    }
}
