//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckLayoutElement
    {
        public int CheckLayoutElementId { get; set; }
        public int CheckLayoutId { get; set; }
        public int CheckLayoutElementTypeListId { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ImageFilename { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CheckLayout CheckLayout { get; set; }
        public virtual CheckLayoutElementTypeList CheckLayoutElementTypeList { get; set; }
    }
}
