//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionPaymentSchedule
    {
        public int CommissionPaymentScheduleId { get; set; }
        public string Description { get; set; }
        public Nullable<int> PaymentScheduleTypeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Term1_StartMonth { get; set; }
        public Nullable<int> Term1_EndMonth { get; set; }
        public Nullable<decimal> Term1_Percent { get; set; }
        public Nullable<int> Term2_StartMonth { get; set; }
        public Nullable<int> Term2_EndMonth { get; set; }
        public Nullable<decimal> Term2_Percent { get; set; }
        public Nullable<int> Term3_StartMonth { get; set; }
        public Nullable<int> Term3_EndMonth { get; set; }
        public Nullable<decimal> Term3_Percent { get; set; }
        public Nullable<int> Term4_StartMonth { get; set; }
        public Nullable<int> Term4_EndMonth { get; set; }
        public Nullable<decimal> Term4_Percent { get; set; }
        public Nullable<int> StatusListId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
