//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionTrx
    {
        public int CommissionTrxId { get; set; }
        public Nullable<int> CommissionScheduleId { get; set; }
        public Nullable<int> CommissionCompensationScheduleId { get; set; }
        public Nullable<int> CompensationTypeListId { get; set; }
        public Nullable<int> CommissionPaymentScheduleId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<decimal> ContractAmount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> SaleAE_UserId { get; set; }
        public Nullable<decimal> CommissionPercentage { get; set; }
        public Nullable<decimal> CommissionAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> PaymentNumber { get; set; }
        public Nullable<int> TotalPaymentNumber { get; set; }
        public Nullable<int> StatusListId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
