//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompensationTypeList
    {
        public int CompensationTypeListId { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusListId { get; set; }
        public Nullable<bool> IncludeinTotalSales { get; set; }
        public Nullable<bool> VariableSales { get; set; }
        public Nullable<bool> CommissionBasedonTotalSale { get; set; }
        public Nullable<bool> UserSpecific { get; set; }
        public Nullable<bool> StartDateSpecific { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> RegionId { get; set; }
    }
}
