//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractDetail
    {
        public int ContractDetailId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> ServiceTypeListId { get; set; }
        public Nullable<int> BillingFrequencyListId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string SquareFootage { get; set; }
        public Nullable<int> CleanTimes { get; set; }
        public Nullable<bool> Mon { get; set; }
        public Nullable<bool> Tues { get; set; }
        public Nullable<bool> Wed { get; set; }
        public Nullable<bool> Thur { get; set; }
        public Nullable<bool> Fri { get; set; }
        public Nullable<bool> Sat { get; set; }
        public Nullable<bool> Sun { get; set; }
        public Nullable<int> CleanFrequencyListId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> BPPAdmin { get; set; }
        public Nullable<bool> CPIIncrease { get; set; }
        public Nullable<bool> AccountRebate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> separateInvoice { get; set; }
        public Nullable<int> CPIMonthApplied { get; set; }
        public Nullable<decimal> CPIPercent { get; set; }
        public Nullable<bool> TaxExcempt { get; set; }
        public Nullable<bool> WeekEnd { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
