//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.ContractDetails = new HashSet<ContractDetail>();
        }
    
        public int ContractId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SoldById { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<int> ContractTypeListId { get; set; }
        public Nullable<bool> Qualified { get; set; }
        public Nullable<int> AccountTypeListId { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ContractDescription { get; set; }
        public Nullable<int> ContractTermMonth { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> StatusListId { get; set; }
        public Nullable<int> AgreementTypeListId { get; set; }
        public Nullable<decimal> InitialCleanAmount { get; set; }
        public Nullable<int> SoldById_Secondary { get; set; }
        public Nullable<int> CommissionTransactionStatusListId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractDetail> ContractDetails { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
