//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountyTaxAuthorityList
    {
        public int CountyTaxAuthorityListId { get; set; }
        public Nullable<decimal> contractrate { get; set; }
        public Nullable<decimal> supplyrate { get; set; }
        public Nullable<decimal> leaserate { get; set; }
        public string county { get; set; }
        public string state { get; set; }
        public string countyname { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    }
}
