//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditTempDetail
    {
        public int CreditTempDetailId { get; set; }
        public Nullable<int> CreditTempId { get; set; }
        public Nullable<int> MasterTrxTypeListId { get; set; }
        public Nullable<int> SourceTypeListId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<int> ServiceTypeListId { get; set; }
        public string DetailDescription { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> TotalFee { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> AmountTypeListId { get; set; }
        public Nullable<bool> TaxDetail { get; set; }
        public Nullable<bool> FeesDetail { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TypelistId { get; set; }
        public Nullable<int> FC_CreditTempDetailId { get; set; }
        public Nullable<int> FC_BillingPayId { get; set; }
        public string FC_TransactionNumber { get; set; }
        public Nullable<int> TransactionStatusListId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> BaseMasterTrxDetailId { get; set; }
    }
}
