//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditFranchisee
    {
        public int CreditFranchiseeId { get; set; }
        public Nullable<int> MasterTrxId { get; set; }
        public Nullable<int> BillingPayId { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public Nullable<int> TransactionStatusListId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TransactionNumber { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string CreditFranchiseeDescription { get; set; }
        public Nullable<int> CreditId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual Franchisee Franchisee { get; set; }
        public virtual MasterTrx MasterTrx { get; set; }
    }
}
