//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_AccountCustomerDetail
    {
        public int CRM_AccountCustomerDetailId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddressLine1 { get; set; }
        public string CompanyAddressLine2 { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyCounty { get; set; }
        public string CompanyState { get; set; }
        public string CompanyZipCode { get; set; }
        public string CompanyEmailAddress { get; set; }
        public string CompanyPhoneNumber { get; set; }
        public string CompanyFaxNumber { get; set; }
        public Nullable<int> NumberOfEmployees { get; set; }
        public Nullable<int> NumberOfLocations { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<int> AccountTypeListId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CRM_AccountId { get; set; }
        public Nullable<System.DateTime> Callback { get; set; }
        public Nullable<bool> AMorPM { get; set; }
        public string GeneralNote { get; set; }
        public string CompanyWebSite { get; set; }
        public string CompanyAddressLine3 { get; set; }
        public string Ext { get; set; }
        public string Title { get; set; }
        public string SicCode { get; set; }
        public string SalesVolume { get; set; }
        public string LineofBusiness { get; set; }
        public string SqFt { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> Purpose { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<decimal> Attmpt_count { get; set; }
        public string lst_attmpt { get; set; }
        public string cb_ampm { get; set; }
        public string cb_time { get; set; }
        public string contextprice { get; set; }
        public string totlocal { get; set; }
        public string trandate { get; set; }
        public string lastcontact { get; set; }
        public string status { get; set; }
        public string callbackby { get; set; }
        public string callbackdate { get; set; }
        public string lastmaildate { get; set; }
        public Nullable<decimal> initclean { get; set; }
        public string contractterm { get; set; }
        public string solddate { get; set; }
        public string mailoutinc { get; set; }
        public string createdate { get; set; }
        public string StartedDate { get; set; }
        public string accttype { get; set; }
        public Nullable<int> CRM_CallResultId { get; set; }
        public string SpokeWith { get; set; }
        public Nullable<int> CRM_NoteTypeId { get; set; }
        public Nullable<int> CRM_SalePossibilityTypeId { get; set; }
        public Nullable<System.DateTime> ContractExpire { get; set; }
        public Nullable<int> TerritoryId { get; set; }
        public string SicDescription { get; set; }
        public Nullable<int> AssigneeId { get; set; }
        public Nullable<int> StageStatus { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> ProviderSource { get; set; }
        public Nullable<int> ProviderType { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string ContactEmail { get; set; }
        public string ContactName { get; set; }
        public Nullable<decimal> CompanyLatitude { get; set; }
        public Nullable<decimal> CompanyLongitude { get; set; }
    }
}
