//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_FranchiseTempData
    {
        public int CRM_FranchiseTempDataId { get; set; }
        public string company_no { get; set; }
        public string regionid { get; set; }
        public string createdate { get; set; }
        public string salutation { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string addr { get; set; }
        public string addr2 { get; set; }
        public string addr3 { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public string hphone { get; set; }
        public string wphone { get; set; }
        public string ext { get; set; }
        public string celphone { get; set; }
        public string email { get; set; }
        public string leadsource { get; set; }
        public string initialcon { get; set; }
        public string infosent { get; set; }
        public string country { get; set; }
        public string countryint { get; set; }
        public string lastcontdt { get; set; }
        public string lastcontby { get; set; }
        public string callbdate { get; set; }
        public string callbby { get; set; }
        public string disclosed { get; set; }
        public string datecanbuy { get; set; }
        public string estclosedat { get; set; }
        public string fivedpaper { get; set; }
        public string status { get; set; }
        public string solddate { get; set; }
        public string soldby { get; set; }
        public string franplan { get; set; }
        public string franamt { get; set; }
        public string downamt { get; set; }
        public string employer { get; set; }
        public string position { get; set; }
        public string schtraindte { get; set; }
        public string jkfullpart { get; set; }
        public string cash2invst { get; set; }
        public string state { get; set; }
        public string f_id { get; set; }
        public string corpgen { get; set; }
        public string mi { get; set; }
        public string mailoutinc { get; set; }
        public string fphone { get; set; }
        public string heardfrom { get; set; }
        public string lastmailda { get; set; }
        public string trandate { get; set; }
        public string investrang { get; set; }
        public string mastrequest { get; set; }
        public string leadnotes { get; set; }
    }
}
