//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Territory_Assignment_New
    {
        public int CRM_TerriAssignmentId { get; set; }
        public Nullable<int> CRM_TerritoryId { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> CRMRgnCardinalDirectionId { get; set; }
    }
}
