//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_tempallregiondata
    {
        public int tempcustomerdataId { get; set; }
        public string company_no { get; set; }
        public string regioncode { get; set; }
        public string enteredby { get; set; }
        public string assignedto { get; set; }
        public string createddate { get; set; }
        public string leadsource { get; set; }
        public string company { get; set; }
        public string accttype { get; set; }
        public string sqrft { get; set; }
        public string salutation { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string title { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string phone { get; set; }
        public string ext { get; set; }
        public string fax { get; set; }
        public string celphone { get; set; }
        public string email { get; set; }
        public string mailoutinc { get; set; }
        public string solddate { get; set; }
        public string startdate { get; set; }
        public string budgetamount { get; set; }
        public string contractterm { get; set; }
        public string initclean { get; set; }
        public string lastmaildate { get; set; }
        public string callbackdate { get; set; }
        public string callbackby { get; set; }
        public string status { get; set; }
        public string lastcontact { get; set; }
        public string currentven { get; set; }
        public string siccode { get; set; }
        public string trandate { get; set; }
        public string totlocal { get; set; }
        public string contextprice { get; set; }
        public string cb_time { get; set; }
        public string cb_ampm { get; set; }
        public string lst_attmpt { get; set; }
        public string attmpt_count { get; set; }
        public string notes { get; set; }
    }
}
