//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_tempImportData
    {
        public int CRM_tempImportDataId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string email { get; set; }
        public string Company { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string WebAddress { get; set; }
        public string Ext { get; set; }
        public string Title { get; set; }
        public string SicCode { get; set; }
        public string SalesVolume { get; set; }
        public string SqFt { get; set; }
        public string LineofBusiness { get; set; }
        public string FaxNumber { get; set; }
        public string CountyCode { get; set; }
        public string SicDescription { get; set; }
        public string CellPhone { get; set; }
        public string AssignedTo { get; set; }
        public string EnteredBy { get; set; }
        public string LeadSource { get; set; }
        public string AccountType { get; set; }
        public string SoldDate { get; set; }
        public string StartDate { get; set; }
        public string BudgetAmount { get; set; }
        public string ContractTam { get; set; }
        public string InitClean { get; set; }
        public string HeardFrom { get; set; }
        public string CallBackDate { get; set; }
        public string CallBackBy { get; set; }
        public string Status { get; set; }
        public string LastContact { get; set; }
        public string CurrentProvider { get; set; }
        public string LastAttempt { get; set; }
        public string Company_no { get; set; }
        public string LeadId { get; set; }
        public string RegionCode { get; set; }
        public string Country { get; set; }
        public string LeadNote { get; set; }
    }
}
