//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_StageStatusSchedule
    {
        public int CRM_StageStatusScheduleId { get; set; }
        public int CRM_AccountCustomerDetailId { get; set; }
        public Nullable<int> CRM_AccountFranchiseDetailId { get; set; }
        public Nullable<int> CRM_InitialCommunicationId { get; set; }
        public Nullable<int> CRM_PdAppointmentId { get; set; }
        public Nullable<int> CRM_FollowUpId { get; set; }
        public Nullable<System.DateTime> Schedule1 { get; set; }
        public Nullable<System.DateTime> Schedule2 { get; set; }
        public Nullable<int> Purpose1 { get; set; }
        public Nullable<int> Purpose2 { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CRM_LeadGenerationId { get; set; }
        public string Title { get; set; }
        public Nullable<int> CRM_BiddingId { get; set; }
    }
}
