//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_SignAgreement
    {
        public int CRM_SignAgreementId { get; set; }
        public Nullable<int> CRM_AccountFranchiseDetailId { get; set; }
        public Nullable<System.DateTime> DateSign { get; set; }
        public Nullable<decimal> Term { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> PlanType { get; set; }
        public Nullable<decimal> PlanAmount { get; set; }
        public Nullable<decimal> IBAmount { get; set; }
        public Nullable<decimal> DownPayment { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> NoOfPayments { get; set; }
        public Nullable<decimal> CurrentPayment { get; set; }
        public Nullable<System.DateTime> PaymentStartDate { get; set; }
        public Nullable<decimal> TriggerAmount { get; set; }
        public Nullable<System.DateTime> legalOblStart { get; set; }
        public Nullable<System.DateTime> LegalOblEnd { get; set; }
        public string LegalOblDue { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> SignFranchiseAgreement { get; set; }
        public Nullable<bool> GuaranteesSigned { get; set; }
        public Nullable<bool> RequiredDocument { get; set; }
        public Nullable<bool> LegalBackGround { get; set; }
    }
}
