//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_CallLog
    {
        public int CRM_CallLogId { get; set; }
        public Nullable<int> CRM_AccountCustomerDetailId { get; set; }
        public int CRM_AccountId { get; set; }
        public Nullable<int> CRM_LeadSource { get; set; }
        public Nullable<int> CRM_CallResultId { get; set; }
        public Nullable<int> CRM_NoteTypeId { get; set; }
        public string SpokeWith { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CallLogDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> StageStatus { get; set; }
        public Nullable<System.DateTime> Callback { get; set; }
        public Nullable<System.DateTime> CallBackTime { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> regionid { get; set; }
        public Nullable<int> leadId { get; set; }
    }
}
