//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Activity
    {
        public int CRM_ActivityId { get; set; }
        public Nullable<int> CRM_AccountCustomerDetailId { get; set; }
        public Nullable<int> ActivityType { get; set; }
        public Nullable<int> OutComeType { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CRM_AccountFranchiseDetailId { get; set; }
        public Nullable<int> RegionId { get; set; }
    }
}
