//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PurposeType
    {
        public int CRM_PurposeTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> CRMStageStatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> CRMInitialCommunication { get; set; }
        public Nullable<bool> CRMLeadGeneration { get; set; }
        public Nullable<bool> CRMPotentialInquary { get; set; }
        public Nullable<bool> CRMFollowup { get; set; }
        public Nullable<bool> CRMFranchiseFollowUp { get; set; }
        public Nullable<bool> PdAppointment { get; set; }
        public Nullable<bool> CRMBidding { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public string ColorCode { get; set; }
        public Nullable<int> StatusListId { get; set; }
    }
}
