//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Tmpterritoryimpdata
    {
        public int CRM_TmpterritoryimpdataId { get; set; }
        public string company_no { get; set; }
        public string grpname { get; set; }
        public string zips { get; set; }
    }
}
