//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSActivity
    {
        public int CSActivityId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public Nullable<int> ValidationItemId { get; set; }
        public Nullable<bool> IsItemChecked { get; set; }
        public Nullable<int> StatusListId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsStaticDesign { get; set; }
        public Nullable<int> StaticDesignItemNo { get; set; }
        public Nullable<bool> StaticDesignIsItemChecked { get; set; }
        public string StaticDesignNote { get; set; }
        public Nullable<System.DateTime> StaticDesignScheduleDate { get; set; }
        public Nullable<System.DateTime> StaticDesignScheduleTime { get; set; }
        public string StaticDesignUpload { get; set; }
        public Nullable<System.DateTime> StaticDesignScheduleEndTime { get; set; }
    }
}
