//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSAccountWalkThursFormFieldDetail
    {
        public int CSAccountWalkThursFormFieldDetailId { get; set; }
        public Nullable<int> CSAccountWalkThursFormFieldId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public Nullable<bool> FieldValue { get; set; }
        public string FieldText { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string FileUrl { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Franchisee Franchisee { get; set; }
    }
}
