//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CusFee
    {
        public int FeesId { get; set; }
        public Nullable<int> Name { get; set; }
        public Nullable<int> FeeRateId { get; set; }
        public Nullable<int> RateType { get; set; }
        public Nullable<decimal> StartRange { get; set; }
        public Nullable<decimal> EndRange { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual FeeRate FeeRate { get; set; }
    }
}
