//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLog
    {
        public int CustomerLogId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> ContactTypeListId { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactMI { get; set; }
        public string ContactLastName { get; set; }
        public string ContactTitle { get; set; }
        public string ContactAttention { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
