//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.BillSettings = new HashSet<BillSetting>();
            this.CommissionSchedules = new HashSet<CommissionSchedule>();
            this.CommissionTrxes = new HashSet<CommissionTrx>();
            this.Contracts = new HashSet<Contract>();
            this.CRM_Account = new HashSet<CRM_Account>();
            this.CSAccountWalkThursFormFieldDetails = new HashSet<CSAccountWalkThursFormFieldDetail>();
            this.CustomerLogs = new HashSet<CustomerLog>();
            this.Distributions = new HashSet<Distribution>();
            this.FindersFees = new HashSet<FindersFee>();
            this.FindersFeeBills = new HashSet<FindersFeeBill>();
            this.FranCalls = new HashSet<FranCall>();
            this.FranchiseeReportDetails = new HashSet<FranchiseeReportDetail>();
            this.FranchiseeReportFinalizedDetails = new HashSet<FranchiseeReportFinalizedDetail>();
            this.InspectionForms = new HashSet<InspectionForm>();
            this.ManualInvoiceTmps = new HashSet<ManualInvoiceTmp>();
            this.MasterTrxTaxes = new HashSet<MasterTrxTax>();
            this.NegativeDues = new HashSet<NegativeDue>();
            this.PaymentGroupCustomers = new HashSet<PaymentGroupCustomer>();
            this.TurnArounds = new HashSet<TurnAround>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> NationalAccount { get; set; }
        public Nullable<bool> Reference { get; set; }
        public Nullable<bool> Parent { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> StatusListId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> sys_cust { get; set; }
        public string Name2 { get; set; }
        public Nullable<int> CustomerImpId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ContractTypeListId { get; set; }
        public Nullable<int> ThirdParty_CompanyId { get; set; }
        public Nullable<int> PayGroup { get; set; }
        public Nullable<int> LogId { get; set; }
        public Nullable<int> CS_CallLogStatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillSetting> BillSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommissionSchedule> CommissionSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommissionTrx> CommissionTrxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_Account> CRM_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSAccountWalkThursFormFieldDetail> CSAccountWalkThursFormFieldDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerLog> CustomerLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Distribution> Distributions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FindersFee> FindersFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FindersFeeBill> FindersFeeBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranCall> FranCalls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseeReportDetail> FranchiseeReportDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseeReportFinalizedDetail> FranchiseeReportFinalizedDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionForm> InspectionForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualInvoiceTmp> ManualInvoiceTmps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterTrxTax> MasterTrxTaxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NegativeDue> NegativeDues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentGroupCustomer> PaymentGroupCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurnAround> TurnArounds { get; set; }
    }
}
