//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int DepositId { get; set; }
        public int RegionId { get; set; }
        public Nullable<int> MasterTrxId { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public int DepositTypeId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int TransactionStatusListId { get; set; }
        public string TransactionNumber { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string PayeeName { get; set; }
        public string PayeeNumber { get; set; }
    
        public virtual MasterTrx MasterTrx { get; set; }
    }
}
