//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_DueNegativeFranchisee
    {
        public int Bill_Month { get; set; }
        public int Bill_Year { get; set; }
        public Nullable<decimal> Due_Franchise { get; set; }
    }
}
