//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_FranchiseTransactionFees
    {
        public Nullable<int> Bill_Month { get; set; }
        public Nullable<int> Bill_Year { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> amount { get; set; }
        public int Type_Id { get; set; }
    }
}
