//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_TaxLiability
    {
        public string Tax_Authority { get; set; }
        public decimal Service_Tax_Rate { get; set; }
        public Nullable<decimal> Service_Non_Taxable_Amount { get; set; }
        public Nullable<decimal> Service_Taxable_Amount { get; set; }
        public Nullable<decimal> Service_Tax_Amount { get; set; }
        public Nullable<decimal> Customer_Service_Taxable_Amount { get; set; }
        public Nullable<decimal> Custmer_Service_Tax_Amount { get; set; }
        public Nullable<decimal> Franchise_Service_Taxable_Amount { get; set; }
        public Nullable<decimal> Franchise_Service_Tax_Amount { get; set; }
        public decimal Supply_Tax_Rate { get; set; }
        public Nullable<decimal> Supply_Taxable_Amount { get; set; }
        public Nullable<decimal> Supply_Tax_Amount { get; set; }
        public Nullable<decimal> Franchise__Supply_Taxable_Amount { get; set; }
        public Nullable<decimal> Franchise_Supply_Tax { get; set; }
        public Nullable<int> Bill_Month { get; set; }
        public Nullable<int> Bill_Year { get; set; }
    }
}
