//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureTypeEmail
    {
        public int FeatureTypeEmailId { get; set; }
        public Nullable<int> FeatureTypeId { get; set; }
        public string FromEmail { get; set; }
        public string ToEmailId { get; set; }
        public Nullable<bool> EmailToCustomer { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> MailMessageTemplateId { get; set; }
    }
}
