//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTypeList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileTypeList()
        {
            this.UploadDocuments = new HashSet<UploadDocument>();
        }
    
        public int FileTypeListId { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsCustomerRequired { get; set; }
        public Nullable<int> CustomerOrderBy { get; set; }
        public Nullable<bool> IsFranchiseeRequired { get; set; }
        public Nullable<int> FranchiseeOrderBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadDocument> UploadDocuments { get; set; }
    }
}
