//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FindersFeeAdjustment
    {
        public int FindersFeeAdjustmentId { get; set; }
        public Nullable<int> FindersFeeId { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public Nullable<int> FindersFeeAdjustmentTypeListId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual FindersFeeAdjustmentTypeList FindersFeeAdjustmentTypeList { get; set; }
        public virtual Franchisee Franchisee { get; set; }
    }
}
