//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FindersFeeSchedule
    {
        public int FindersFeeScheduleId { get; set; }
        public Nullable<int> FindersFeeTypeListId { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<decimal> DownPayPercentage { get; set; }
        public Nullable<decimal> MonthlyPercentage { get; set; }
        public Nullable<decimal> StartAmount { get; set; }
        public Nullable<decimal> EndAmount { get; set; }
        public Nullable<int> NumOfPayments { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual FindersFeeTypeList FindersFeeTypeList { get; set; }
    }
}
