//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormItemTemplate
    {
        public int FormItemTemplateId { get; set; }
        public int FormTemplateId { get; set; }
        public Nullable<int> FormItemTypeId { get; set; }
        public string FormValue { get; set; }
        public Nullable<int> ItemOrder { get; set; }
        public Nullable<int> SectionOrder { get; set; }
        public string SectionName { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> FormCustomItemTemplateId { get; set; }
    
        public virtual FormTemplate FormTemplate { get; set; }
    }
}
