//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseeReportGenerateDetail
    {
        public int FranchiseeReportGenerateDetailId { get; set; }
        public Nullable<int> FranchiseeReportGenerateId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> BillMonth { get; set; }
        public Nullable<int> BillYear { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public Nullable<int> ServiceTypeListId { get; set; }
        public string ServiceType { get; set; }
        public Nullable<bool> IsDeduction { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> DisplaySubReport { get; set; }
        public string Description { get; set; }
        public string DescriptionMisc { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> AmountTypeListId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> MasterTrxTypeListId { get; set; }
        public Nullable<int> MasterTrxDetailId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> BillingPayId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<int> IsCommission { get; set; }
        public Nullable<int> ReSell { get; set; }
        public Nullable<System.DateTime> LeaseDate { get; set; }
        public string LeaseNo { get; set; }
        public string LeaseSerialNo { get; set; }
        public string CurrentPaymentNo { get; set; }
        public Nullable<int> TotalPaymentNo { get; set; }
        public Nullable<int> MasterTrxFeeDetailId { get; set; }
        public Nullable<int> FeeId { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
        public Nullable<bool> FRRevenues { get; set; }
        public Nullable<bool> FRDeduction { get; set; }
        public Nullable<bool> IsTransactionFee { get; set; }
        public Nullable<bool> BPPAdmin { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> ServiceTypeGroupListId { get; set; }
        public Nullable<bool> DisplayLeaseMessage { get; set; }
    }
}
