//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseeReport
    {
        public int FranchiseeReportId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> BillMonth { get; set; }
        public Nullable<int> BillYear { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public string FranchiseeNo { get; set; }
        public string FranchiseeName { get; set; }
        public string FranchiseeAddress1 { get; set; }
        public string FranchiseeAddress2 { get; set; }
        public string FranchiseeContractPlanType { get; set; }
        public Nullable<System.DateTime> FranchiseeContractSignDate { get; set; }
        public Nullable<int> IsFinalized { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> TotalDeductions { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> FinalizedBy { get; set; }
        public Nullable<System.DateTime> FinalizedDate { get; set; }
        public int TransactionStatusListId { get; set; }
        public Nullable<decimal> AccountingFeeRebateAmount { get; set; }
        public Nullable<decimal> AccountingFeeRebateBalance { get; set; }
        public Nullable<bool> MinimumRoyalty { get; set; }
    
        public virtual Franchisee Franchisee { get; set; }
    }
}
