//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranCall
    {
        public int FranCallId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public Nullable<System.DateTime> call_date { get; set; }
        public Nullable<System.TimeSpan> call_time { get; set; }
        public string call_stat { get; set; }
        public Nullable<int> StatusResultListId { get; set; }
        public string spoke_with { get; set; }
        public string call_back { get; set; }
        public string call_btime { get; set; }
        public string action { get; set; }
        public string action_otr { get; set; }
        public string init_call { get; set; }
        public string comments { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<bool> IsCallBack { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Franchisee Franchisee { get; set; }
    }
}
