//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Franchisee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Franchisee()
        {
            this.Chargebacks = new HashSet<Chargeback>();
            this.CreditFranchisees = new HashSet<CreditFranchisee>();
            this.CSAccountWalkThursFormFieldDetails = new HashSet<CSAccountWalkThursFormFieldDetail>();
            this.Distributions = new HashSet<Distribution>();
            this.FindersFees = new HashSet<FindersFee>();
            this.FindersFeeAdjustments = new HashSet<FindersFeeAdjustment>();
            this.FindersFeeBills = new HashSet<FindersFeeBill>();
            this.FranCalls = new HashSet<FranCall>();
            this.FranchiseeBillSettings = new HashSet<FranchiseeBillSetting>();
            this.FranchiseeContracts = new HashSet<FranchiseeContract>();
            this.FranchiseeFees = new HashSet<FranchiseeFee>();
            this.FranchiseeOwnerLists = new HashSet<FranchiseeOwnerList>();
            this.FranchiseeReports = new HashSet<FranchiseeReport>();
            this.FranchiseeReportDetails = new HashSet<FranchiseeReportDetail>();
            this.FranchiseeReportFinalizeds = new HashSet<FranchiseeReportFinalized>();
            this.FranchiseeReportFinalizedDetails = new HashSet<FranchiseeReportFinalizedDetail>();
            this.FranchiseeTurnaroundChecks = new HashSet<FranchiseeTurnaroundCheck>();
            this.InspectionForms = new HashSet<InspectionForm>();
            this.ManualInvoiceTmpDistributions = new HashSet<ManualInvoiceTmpDistribution>();
            this.PaymentBillingFranchisees = new HashSet<PaymentBillingFranchisee>();
            this.TurnArounds = new HashSet<TurnAround>();
        }
    
        public int FranchiseeId { get; set; }
        public string FranchiseeNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> StatusListId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> dlr_id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> FranchiseeTypeListId { get; set; }
        public Nullable<int> LogId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> Perfix { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chargeback> Chargebacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditFranchisee> CreditFranchisees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSAccountWalkThursFormFieldDetail> CSAccountWalkThursFormFieldDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Distribution> Distributions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FindersFee> FindersFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FindersFeeAdjustment> FindersFeeAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FindersFeeBill> FindersFeeBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranCall> FranCalls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseeBillSetting> FranchiseeBillSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseeContract> FranchiseeContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseeFee> FranchiseeFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseeOwnerList> FranchiseeOwnerLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseeReport> FranchiseeReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseeReportDetail> FranchiseeReportDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseeReportFinalized> FranchiseeReportFinalizeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseeReportFinalizedDetail> FranchiseeReportFinalizedDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseeTurnaroundCheck> FranchiseeTurnaroundChecks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionForm> InspectionForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualInvoiceTmpDistribution> ManualInvoiceTmpDistributions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentBillingFranchisee> PaymentBillingFranchisees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurnAround> TurnArounds { get; set; }
    }
}
