//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseeFullfillment
    {
        public int FranchiseeFullfillmentId { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public Nullable<System.DateTime> BackgroundCheckDate { get; set; }
        public Nullable<System.DateTime> BusinessProtectionDate { get; set; }
        public Nullable<System.DateTime> TrainingDate { get; set; }
        public Nullable<System.DateTime> BusinessLicensedate { get; set; }
        public Nullable<System.DateTime> EquipmentAndSupplyDate { get; set; }
    }
}
