//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseeContractTypeList
    {
        public int FranchiseeContractTypeListId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> BusinessAmount { get; set; }
        public Nullable<decimal> DownPayment { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<int> NoOfPayments { get; set; }
        public Nullable<int> DaysToFullfill { get; set; }
    }
}
