//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseeManualTransaction
    {
        public int FranchiseeManualTransactionId { get; set; }
        public Nullable<int> MasterTrxId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public Nullable<int> ServiceTypeListId { get; set; }
        public string TransactionNumber { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> TransactionStatusListId { get; set; }
        public string FranchiseeManualTransactionDescription { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> MasterTrxTypeListId { get; set; }
        public Nullable<int> FranchiseeManualTrxCreditReasonListId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<bool> ReSell { get; set; }
        public Nullable<int> FranchiseeMnaualImpId { get; set; }
        public string VendorInvoiceNumber { get; set; }
        public Nullable<System.DateTime> VendorInvoiceDate { get; set; }
        public Nullable<bool> IsCredit { get; set; }
        public Nullable<int> FranchsieeTrxTypeListId { get; set; }
        public string VendorCode { get; set; }
    
        public virtual MasterTrx MasterTrx { get; set; }
    }
}
