//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseeContract
    {
        public int FranchiseeContractId { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public Nullable<int> FranchiseeContractTypeListId { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<System.DateTime> DateSign { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> IBAmount { get; set; }
        public Nullable<decimal> DownPaymentAmount { get; set; }
        public Nullable<decimal> MonthlyPaymentAmount { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<int> TotalPayments { get; set; }
        public Nullable<int> PaymentsBilled { get; set; }
        public Nullable<decimal> TriggerAmount { get; set; }
        public Nullable<decimal> LegalObligationAmount { get; set; }
        public Nullable<decimal> LegalObligaitonDueAmount { get; set; }
        public Nullable<System.DateTime> LegalObligationStartDate { get; set; }
        public Nullable<System.DateTime> LegalObligationEndDate { get; set; }
        public Nullable<int> ContractStatusListId { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string statusNotes { get; set; }
        public Nullable<System.DateTime> ResumeDate { get; set; }
        public Nullable<int> ContractStatusReasonListId { get; set; }
        public Nullable<System.DateTime> GraceDateStart { get; set; }
        public Nullable<System.DateTime> GraceDateEnd { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<decimal> CurrentPayment { get; set; }
        public Nullable<int> DaysToFullfill { get; set; }
        public Nullable<System.DateTime> LastRenewedContractDate { get; set; }
    
        public virtual Franchisee Franchisee { get; set; }
    }
}
