//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionFormItem
    {
        public int InspectionFormItemId { get; set; }
        public Nullable<int> InspectionFormSectionId { get; set; }
        public int FormItemType { get; set; }
        public Nullable<int> FormItemOrder { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string FormItemValue { get; set; }
        public Nullable<bool> IsDirty { get; set; }
        public Nullable<bool> IsRequired { get; set; }
    }
}
