//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionForm
    {
        public int InspectionFormId { get; set; }
        public Nullable<int> ServiceTypeListId { get; set; }
        public Nullable<int> AccountTypeListId { get; set; }
        public string FormName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> PassPoints { get; set; }
        public Nullable<decimal> FailPoints { get; set; }
        public Nullable<decimal> NeedImprovementPoints { get; set; }
        public Nullable<decimal> ScorePercent { get; set; }
        public string SignatureUrl { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public Nullable<System.DateTime> RecordedDate { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<int> InspectionStatusId { get; set; }
        public Nullable<int> JobId { get; set; }
        public string InspectedBy { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public Nullable<int> InspectorId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Franchisee Franchisee { get; set; }
    }
}
