//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceMessage
    {
        public string Message { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public int InvoiceMessageId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> MessageId { get; set; }
        public Nullable<int> MessageDetailId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
