//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockboxEDI
    {
        public int LockboxEDIId { get; set; }
        public Nullable<System.DateTime> LockboxDate { get; set; }
        public string LockboxFileName { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string RegionName { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
        public Nullable<bool> HasError { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
        public string LockboxData { get; set; }
        public string LockboxKey { get; set; }
        public Nullable<int> StatusListId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
