//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMsg
    {
        public int LogMsgID { get; set; }
        public Nullable<int> LogListId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TypelistID { get; set; }
        public Nullable<int> ServiceCallLogTypeListId { get; set; }
        public string Massaqe { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
