//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceTemp
    {
        public int MaintenanceTempId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public Nullable<int> StatusListId { get; set; }
        public Nullable<int> StatusReasonListId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ResumeDate { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RequestChangeStatusListId { get; set; }
        public Nullable<int> RequestChangeNotes { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> MaintenanceTypeListId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Reason { get; set; }
        public Nullable<int> MaintenanceStatusListId { get; set; }
        public Nullable<int> PeriodId { get; set; }
    
        public virtual RequestChangeStatusList RequestChangeStatusList { get; set; }
    }
}
