//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceTempDetail
    {
        public int MaintenanceTempDetailId { get; set; }
        public int MaintenanceTempId { get; set; }
        public int MaintenanceDetailTypeListId { get; set; }
        public string RecordType { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string CPONumber { get; set; }
        public Nullable<int> CAccountTypeListId { get; set; }
        public Nullable<bool> CQualified { get; set; }
        public Nullable<System.DateTime> CSignDate { get; set; }
        public Nullable<System.DateTime> CStartDate { get; set; }
        public Nullable<System.DateTime> CExpirationDate { get; set; }
        public Nullable<int> CContractTermMonth { get; set; }
        public Nullable<decimal> CTotalAmount { get; set; }
        public Nullable<decimal> COTotalAmount { get; set; }
        public string CContractDescription { get; set; }
        public Nullable<int> ContractDetailId { get; set; }
        public Nullable<int> CDLineNumber { get; set; }
        public Nullable<int> CDServiceTypeListId { get; set; }
        public Nullable<int> CDBillingFrequencyListId { get; set; }
        public string CDSquareFootage { get; set; }
        public Nullable<decimal> CDAmount { get; set; }
        public Nullable<decimal> CDOAmount { get; set; }
        public Nullable<System.DateTime> CDStartTime { get; set; }
        public Nullable<System.DateTime> CDEndTime { get; set; }
        public Nullable<int> CDCleanTimes { get; set; }
        public Nullable<int> CDCleanFrequencyListId { get; set; }
        public Nullable<bool> CDMon { get; set; }
        public Nullable<bool> CDTues { get; set; }
        public Nullable<bool> CDWed { get; set; }
        public Nullable<bool> CDThur { get; set; }
        public Nullable<bool> CDFri { get; set; }
        public Nullable<bool> CDSat { get; set; }
        public Nullable<bool> CDSun { get; set; }
        public Nullable<bool> CDCPIIncrease { get; set; }
        public Nullable<bool> CDSeparateInvoice { get; set; }
        public string CDDescription { get; set; }
        public string CDNotes { get; set; }
        public Nullable<int> DistributionId { get; set; }
        public Nullable<int> DContractDetailId { get; set; }
        public Nullable<int> DFranchiseeId { get; set; }
        public Nullable<decimal> DAmount { get; set; }
        public Nullable<decimal> DFeeAmount { get; set; }
        public Nullable<decimal> DTotalAmount { get; set; }
        public Nullable<int> DInvoiceId { get; set; }
        public string FeeId { get; set; }
        public Nullable<int> DFFeeRateTypeListId { get; set; }
        public Nullable<decimal> DFAmount { get; set; }
        public Nullable<int> FindersFeeId { get; set; }
        public Nullable<int> FFTransactionStatusListId { get; set; }
        public Nullable<System.DateTime> FFStartDate { get; set; }
        public Nullable<System.DateTime> FFResumeDate { get; set; }
        public Nullable<int> FFFindersFeeTypeListId { get; set; }
        public Nullable<decimal> FFContractBillingAmount { get; set; }
        public Nullable<decimal> FFTotalAdjustmentAmount { get; set; }
        public Nullable<decimal> FFPayableOnAmount { get; set; }
        public Nullable<decimal> FFFactor { get; set; }
        public Nullable<decimal> FFInterest { get; set; }
        public Nullable<decimal> FFInterestAmount { get; set; }
        public Nullable<int> FFTotalNumOfpayments { get; set; }
        public Nullable<decimal> FFMonthlyPaymentPercentage { get; set; }
        public Nullable<decimal> FFMonthlyPaymentAmount { get; set; }
        public Nullable<decimal> FFDownPayPercentage { get; set; }
        public Nullable<decimal> FFDownPaymentAmount { get; set; }
        public Nullable<decimal> FFFinancedAmount { get; set; }
        public Nullable<decimal> FFTotalAmount { get; set; }
        public Nullable<decimal> FFMultiTenantOccupancyAmount { get; set; }
        public Nullable<decimal> FFPaidAmount { get; set; }
        public Nullable<decimal> FFBalanceAmount { get; set; }
        public Nullable<System.DateTime> FFStopDate { get; set; }
        public Nullable<decimal> FFAmount { get; set; }
        public string FFNotes { get; set; }
        public Nullable<bool> FFIncludeDownPayInFirstPay { get; set; }
        public Nullable<bool> FFIsTroubleWithFee { get; set; }
        public Nullable<bool> FFIsIsTroubleWithoutFee { get; set; }
        public Nullable<bool> FFIsNotATroubleAccount { get; set; }
        public Nullable<decimal> FFTroubleWithFeeAmount { get; set; }
        public Nullable<bool> FFIsCancellationFee { get; set; }
        public Nullable<decimal> FFCancellationFeeAmount { get; set; }
        public Nullable<int> FindersFeeAdjustmentId { get; set; }
        public Nullable<int> FFAdjustmentTypeListId { get; set; }
        public string FFADescription { get; set; }
        public Nullable<decimal> FFAAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CRReasonId { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRDescription { get; set; }
        public Nullable<int> CRContractDetailId { get; set; }
        public Nullable<int> CRLineNumber { get; set; }
        public Nullable<decimal> CRApplyAmount { get; set; }
        public Nullable<decimal> CRTaxAmount { get; set; }
        public Nullable<int> CRFranchiseeId { get; set; }
        public Nullable<int> CRInvoiceId { get; set; }
        public Nullable<decimal> CRAmount { get; set; }
        public Nullable<int> INV_BillMonth { get; set; }
        public Nullable<int> INV_BillYear { get; set; }
        public Nullable<System.DateTime> INV_InvoiceDate { get; set; }
        public string INV_InvoiceDescription { get; set; }
        public Nullable<int> INV_AccountTypeListId { get; set; }
        public Nullable<int> INV_MasterTrxTypeListId { get; set; }
        public Nullable<int> INV_PeriodId { get; set; }
        public Nullable<int> INV_TaxRateId { get; set; }
        public Nullable<int> INV_CustomerTransactionId { get; set; }
        public Nullable<int> INV_LineNo { get; set; }
        public Nullable<int> INV_ServiceTypeListId { get; set; }
        public Nullable<decimal> INV_UnitPrice { get; set; }
        public Nullable<int> INV_Quantity { get; set; }
        public Nullable<decimal> INV_MarkUpTotal { get; set; }
        public Nullable<decimal> INV_ExtendedPrice { get; set; }
        public Nullable<decimal> INV_TaxAmount { get; set; }
        public Nullable<decimal> INV_Total { get; set; }
        public string INV_Description { get; set; }
        public Nullable<int> INV_TransactionStatusListId { get; set; }
        public Nullable<int> INV_TaxRate { get; set; }
        public Nullable<decimal> INV_TaxPercentage { get; set; }
        public Nullable<bool> INV_Commission { get; set; }
        public Nullable<decimal> INV_CommissionTotal { get; set; }
        public Nullable<bool> INV_ExtraWork { get; set; }
        public Nullable<bool> INV_TaxExcempt { get; set; }
        public Nullable<bool> INV_BPPAdmin { get; set; }
        public Nullable<bool> INV_AccountRebate { get; set; }
        public Nullable<bool> INV_PrintInvoice { get; set; }
        public Nullable<int> INV_FranchiseeTransactionId { get; set; }
        public Nullable<int> INV_FranchiseeId { get; set; }
        public Nullable<bool> INV_IsDelete { get; set; }
    }
}
