//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualInvoiceTmp
    {
        public int ManualInvoiceTmpId { get; set; }
        public Nullable<int> MasterTrxTypeListId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> TransactionStatusListId { get; set; }
        public Nullable<int> AccountTypeListId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceDescription { get; set; }
        public Nullable<int> TaxRateId { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<int> BillMonth { get; set; }
        public Nullable<int> BillYear { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> MaintenanceTempId { get; set; }
        public Nullable<int> GeneratedInvoiceId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
