//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualInvoiceTmpDetail
    {
        public int ManualInvoiceTmpDetailId { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<int> ServiceTypeListId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> MarkUpTotal { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> TaxExcempt { get; set; }
        public Nullable<bool> BPPAdmin { get; set; }
        public Nullable<bool> AccountRebate { get; set; }
        public Nullable<bool> PrintInvoice { get; set; }
        public Nullable<bool> Commission { get; set; }
        public Nullable<decimal> CommissionTotal { get; set; }
        public Nullable<bool> ExtraWork { get; set; }
        public Nullable<int> ManualInvoiceTmpId { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> ClientSupplies { get; set; }
    }
}
