//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterTrxTypeList
    {
        public int MasterTrxTypeListId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public Nullable<int> AmountTypeListId { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> AmountTypeListIdMasterTrxTax { get; set; }
        public Nullable<int> AmountTypeListIdMasterTrxFeeDetail { get; set; }
        public Nullable<bool> FRRevenues { get; set; }
        public Nullable<bool> FRDeduction { get; set; }
        public Nullable<bool> ECheck { get; set; }
        public Nullable<bool> FranchiseDetailView { get; set; }
        public Nullable<bool> CustomerDetailView { get; set; }
        public Nullable<int> Debit_GLId { get; set; }
        public Nullable<int> Credit_GLId { get; set; }
        public Nullable<int> Credit_TaxGLId { get; set; }
        public Nullable<int> Debit_FeeGLId { get; set; }
    }
}
