//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageDetail
    {
        public int MessageDetailId { get; set; }
        public Nullable<int> MessageId { get; set; }
        public string Message { get; set; }
        public Nullable<int> MessageTypeListId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Message Message1 { get; set; }
        public virtual MessageTypeList MessageTypeList { get; set; }
    }
}
