//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationMessage
    {
        public int MessageId { get; set; }
        public Nullable<int> PendingNoteId { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsView { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public Nullable<int> UID { get; set; }
        public string EntrySource { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public Nullable<int> MasterTrxTypeListId { get; set; }
        public Nullable<int> HeaderId { get; set; }
        public Nullable<int> MasterTmpTrxId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> NotificationTypeListId { get; set; }
    }
}
