//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offering
    {
        public int OfferingId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> StatusListId { get; set; }
        public Nullable<System.DateTime> OfferedDate { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> CanceledDate { get; set; }
        public Nullable<int> StatusReasonListId { get; set; }
        public Nullable<decimal> ContractBillingAmount { get; set; }
        public Nullable<bool> InitialBusiness { get; set; }
        public Nullable<decimal> InitialBusinessAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public string AcceptedNote { get; set; }
        public Nullable<System.DateTime> DeclinedDate { get; set; }
        public Nullable<int> DeclineReasonListId { get; set; }
        public string DeclineReasonNote { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> ExpireTime { get; set; }
        public string SpecialNote { get; set; }
    }
}
