//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTransaction()
        {
            this.OrderTransactionsResponses = new HashSet<OrderTransactionsResponse>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid FKPaymentProfileID { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> PriceWithTax { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTransactionsResponse> OrderTransactionsResponses { get; set; }
        public virtual PaymentProfileDetail PaymentProfileDetail { get; set; }
    }
}
