//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTransactionsResponse
    {
        public System.Guid OrderTxReponseID { get; set; }
        public System.Guid FKOrderID { get; set; }
        public System.Guid FKPaymentProfileID { get; set; }
        public string ResponseCode { get; set; }
        public string AuthCode { get; set; }
        public string AvsResultCode { get; set; }
        public string CvvResultCode { get; set; }
        public string CavvResultCode { get; set; }
        public string TransId { get; set; }
        public string RefTransId { get; set; }
        public string TransHash { get; set; }
        public string AccountNumber { get; set; }
        public string EntryMode { get; set; }
        public string AccountType { get; set; }
        public string TMessagesCode { get; set; }
        public string TMessagesDescription { get; set; }
        public string MessagesResultCode { get; set; }
        public string MessagesCode { get; set; }
        public string MessagesText { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual OrderTransaction OrderTransaction { get; set; }
        public virtual PaymentProfileDetail PaymentProfileDetail { get; set; }
    }
}
