//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentProfileDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentProfileDetail()
        {
            this.OrderTransactions = new HashSet<OrderTransaction>();
            this.OrderTransactionsResponses = new HashSet<OrderTransactionsResponse>();
        }
    
        public System.Guid Id { get; set; }
        public int FKClassId { get; set; }
        public int FKTypeListId { get; set; }
        public int FKPaymentGatewayID { get; set; }
        public string AccountNumber { get; set; }
        public string AccountType { get; set; }
        public string CustomerProfileID { get; set; }
        public string CustomerPaymentProfileID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTransaction> OrderTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTransactionsResponse> OrderTransactionsResponses { get; set; }
        public virtual PaymentGatewayDetail PaymentGatewayDetail { get; set; }
        public virtual TypeList TypeList { get; set; }
    }
}
