//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGroupCustomer
    {
        public int PaymentGroupCustomerId { get; set; }
        public Nullable<int> PaymentGroupId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PayGroup { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
