//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTempDetail
    {
        public int PaymentTempDetailId { get; set; }
        public Nullable<int> MasterTrxId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> MasterTrxTypeListId { get; set; }
        public Nullable<int> HeaderId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> SourceTypeListId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<int> ServiceTypeListId { get; set; }
        public string DetailDescription { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> CPIPercentage { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public Nullable<decimal> DistributionAmount { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> TotalFee { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> AmountTypeListId { get; set; }
        public Nullable<bool> TaxDetail { get; set; }
        public Nullable<bool> FeesDetail { get; set; }
        public Nullable<int> BPPAdmin { get; set; }
        public Nullable<int> AccountRebate { get; set; }
        public Nullable<bool> Commission { get; set; }
        public Nullable<int> ExtraWork { get; set; }
        public Nullable<decimal> CommissionTotal { get; set; }
        public Nullable<int> MasterTrxStatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> ImpAppFromInvId { get; set; }
        public Nullable<bool> FRRevenues { get; set; }
        public Nullable<bool> FRDeduction { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TypelistId { get; set; }
        public Nullable<System.DateTime> Transactiondate { get; set; }
        public Nullable<bool> ReSell { get; set; }
        public Nullable<int> PrimaryPaymentId { get; set; }
        public Nullable<bool> ClientSupplies { get; set; }
        public Nullable<int> MCustomerId { get; set; }
        public Nullable<int> MFranchiseeId { get; set; }
        public Nullable<decimal> PayFranchisee { get; set; }
        public Nullable<int> TurnaroundPaymentStatusListId { get; set; }
        public Nullable<int> TransactionStatusListId { get; set; }
    }
}
