//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGatewayDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentGatewayDetail()
        {
            this.PaymentProfileDetails = new HashSet<PaymentProfileDetail>();
        }
    
        public int Id { get; set; }
        public string PaymentGateway { get; set; }
        public string LoginID { get; set; }
        public string TransactionKey { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int IsDelete { get; set; }
        public string merchantid { get; set; }
        public Nullable<int> RegionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentProfileDetail> PaymentProfileDetails { get; set; }
    }
}
