//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionConfiguration
    {
        public int RegionConfigurationId { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public Nullable<int> valuetype { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> applied { get; set; }
        public Nullable<int> rcgroup { get; set; }
    }
}
