//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Region()
        {
            this.AuthGroupRegions = new HashSet<AuthGroupRegion>();
            this.AuthUserRegions = new HashSet<AuthUserRegion>();
            this.CRMContacts = new HashSet<CRMContact>();
        }
    
        public int RegionId { get; set; }
        public string Name { get; set; }
        public string Acronym { get; set; }
        public Nullable<int> Corporate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Test { get; set; }
        public string Displayname { get; set; }
        public string ReportName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> RemitSameAsMain { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Phone { get; set; }
        public Nullable<int> International { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string AhPhone { get; set; }
        public string Fax { get; set; }
        public string Director { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string DBname { get; set; }
        public string LockboxId { get; set; }
        public Nullable<int> Number { get; set; }
        public string company_no { get; set; }
        public string TRVDBName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthGroupRegion> AuthGroupRegions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthUserRegion> AuthUserRegions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMContact> CRMContacts { get; set; }
    }
}
