//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTypeList
    {
        public int ServiceTypeListid { get; set; }
        public string name { get; set; }
        public string acronym { get; set; }
        public string level { get; set; }
        public Nullable<int> taxid { get; set; }
        public string taxtype { get; set; }
        public Nullable<int> regionconfigid { get; set; }
        public string deductiontype { get; set; }
        public Nullable<int> displayorder { get; set; }
        public Nullable<int> displaysubreport { get; set; }
        public Nullable<int> ServiceTypeGroupListId { get; set; }
        public Nullable<int> contracttype { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<bool> CRMLead { get; set; }
        public Nullable<bool> FranchiseeManualTransaction { get; set; }
        public Nullable<bool> IsCredit { get; set; }
        public Nullable<bool> IsDeposit { get; set; }
        public Nullable<bool> IsCBCredit { get; set; }
        public Nullable<bool> CreateFranchiseeManualTransaction { get; set; }
    }
}
