//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRate
    {
        public int TaxRateId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<decimal> ContractTaxRate { get; set; }
        public Nullable<decimal> LeaseTaxRate { get; set; }
        public Nullable<decimal> SupplyTaxRate { get; set; }
        public Nullable<decimal> taxSales { get; set; }
        public Nullable<decimal> taxUse { get; set; }
        public Nullable<decimal> stateSalesTax { get; set; }
        public Nullable<decimal> stateUseTax { get; set; }
        public Nullable<decimal> citySalesTax { get; set; }
        public Nullable<decimal> cityUseTax { get; set; }
        public Nullable<decimal> countySalesTax { get; set; }
        public Nullable<decimal> countyUseTax { get; set; }
        public Nullable<decimal> districtSalesTax { get; set; }
        public Nullable<decimal> districtUseTax { get; set; }
        public Nullable<int> classId { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string County { get; set; }
        public string CountyTaxCode { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> TaxAPIExceptionCode { get; set; }
        public string TaxAPIExceptionReason { get; set; }
        public string TaxAPIExceptionDesc { get; set; }
    }
}
