//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionNumberConfig
    {
        public int TransactionNumberConfigId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> RegionNumber { get; set; }
        public Nullable<int> MasterTrxTypeListId { get; set; }
        public string Name { get; set; }
        public string Prefix { get; set; }
        public Nullable<long> LastNumber { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
