//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnAround
    {
        public int TurnAroundId { get; set; }
        public Nullable<int> MasterTrxId { get; set; }
        public Nullable<int> ChargebackId { get; set; }
        public Nullable<int> PaymentBillingFranchiseeId { get; set; }
        public Nullable<int> TransactionStatusListId { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string TransactionNumber { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> FeeTotal { get; set; }
        public Nullable<decimal> NegativeDueAmount { get; set; }
        public Nullable<decimal> TurnAroundAmount { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> NegativeDueId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> ChargebackAmount { get; set; }
        public Nullable<int> BillingPayId { get; set; }
        public Nullable<int> MasterTrxDetailId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Franchisee Franchisee { get; set; }
        public virtual MasterTrx MasterTrx { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
