//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AR_CustomerTransaction
    {
        public int CustomerTransactionTmpId { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> BillMonth { get; set; }
        public Nullable<int> BillYear { get; set; }
        public int ServiceTypeListId { get; set; }
        public string ServiceName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> MarkUpTotal { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> TaxExcempt { get; set; }
        public Nullable<bool> BPPAdmin { get; set; }
        public Nullable<bool> AccountRebate { get; set; }
        public Nullable<bool> Commission { get; set; }
        public Nullable<decimal> CommissionTotal { get; set; }
        public Nullable<bool> ExtraWork { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> TransactionStatusListId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public int MasterTmpTrxId { get; set; }
        public Nullable<int> TaxRate { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public string InvoiceDescription { get; set; }
        public int CustomerId { get; set; }
        public string CustomerNo { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateName { get; set; }
        public string PostalCode { get; set; }
        public string BName { get; set; }
        public string Attention { get; set; }
        public string BAddress1 { get; set; }
        public string BAddress2 { get; set; }
        public string BCity { get; set; }
        public string BStateName { get; set; }
        public string BPostalCode { get; set; }
        public Nullable<decimal> ContractTaxRate { get; set; }
        public Nullable<decimal> LeaseTaxRate { get; set; }
        public Nullable<decimal> SupplyTaxRate { get; set; }
        public Nullable<bool> PrintInvoice { get; set; }
        public Nullable<int> TaxRateId { get; set; }
        public Nullable<bool> ClientSupplies { get; set; }
    }
}
