//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ChartofAccounts
    {
        public int AccountId { get; set; }
        public int PerentAccountId { get; set; }
        public Nullable<int> AccountNo { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsSubAccount { get; set; }
        public string Attach { get; set; }
        public int TypeId { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> BalanceTotal { get; set; }
    }
}
