//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_C_CustomerMaintenanceList
    {
        public int CustomerId { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerState { get; set; }
        public string CustomerPincode { get; set; }
        public string CustomerBillingName { get; set; }
        public string CustomerBillingAddress { get; set; }
        public string CustomerBillingCity { get; set; }
        public string CustomerBillingState { get; set; }
        public string CustomerBillingPincode { get; set; }
        public Nullable<int> FindersFeeId { get; set; }
        public Nullable<int> ServiceTypeListid { get; set; }
        public string ServiceTypeListName { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public string FranchiseeNo { get; set; }
        public string FranchiseeName { get; set; }
        public Nullable<bool> HasCancellationFee { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> StatusListId { get; set; }
        public string StatusListName { get; set; }
        public Nullable<int> ReasonListId { get; set; }
        public string ReasonListName { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string StatusNotes { get; set; }
        public Nullable<System.DateTime> ResumeDate { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
