//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_C_BillRunConfig
    {
        public int id { get; set; }
        public Nullable<int> billmonth { get; set; }
        public Nullable<int> billyear { get; set; }
        public string nextavinvoice { get; set; }
        public Nullable<int> billrungenerated { get; set; }
        public Nullable<System.DateTime> billrundate { get; set; }
        public Nullable<int> franchiseereportsfinalized { get; set; }
        public Nullable<int> franchiseerptsgenerated { get; set; }
        public Nullable<System.DateTime> franchiseerptsdate { get; set; }
        public Nullable<int> chargebackgenerated { get; set; }
        public Nullable<System.DateTime> chargebackgenerateddate { get; set; }
        public Nullable<int> posted { get; set; }
        public Nullable<System.DateTime> posteddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> checksposted { get; set; }
        public Nullable<System.DateTime> checksposteddate { get; set; }
        public Nullable<int> checksgenerated { get; set; }
        public Nullable<int> monthlytar { get; set; }
    }
}
