//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_C_information
    {
        public int id { get; set; }
        public int regionId { get; set; }
        public string customerNo { get; set; }
        public string name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string county { get; set; }
        public string state { get; set; }
        public Nullable<int> stateId { get; set; }
        public string postalcode { get; set; }
        public Nullable<int> countryId { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public Nullable<int> classtypeId { get; set; }
        public Nullable<int> sameServiceAddress { get; set; }
        public Nullable<int> sameBillingAddress { get; set; }
        public Nullable<int> sameBillingContact { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> parentid { get; set; }
        public Nullable<int> nationalaccount { get; set; }
        public Nullable<int> reference { get; set; }
        public string notes { get; set; }
        public int createdby { get; set; }
        public System.DateTime createdate { get; set; }
        public int modifiedby { get; set; }
        public System.DateTime modifieddate { get; set; }
        public Nullable<int> bppadminFee { get; set; }
        public Nullable<System.DateTime> statusdate { get; set; }
        public string statusnotes { get; set; }
        public Nullable<System.DateTime> resumedate { get; set; }
        public Nullable<int> reasonid { get; set; }
        public Nullable<int> createinvoice { get; set; }
        public Nullable<int> printinvoice { get; set; }
        public Nullable<int> printpastdue { get; set; }
        public Nullable<int> parent { get; set; }
        public Nullable<System.DateTime> lastservicedate { get; set; }
    }
}
