//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_C_Trx
    {
        public int id { get; set; }
        public int trxrecurringid { get; set; }
        public int customerid { get; set; }
        public Nullable<int> serviceLocationid { get; set; }
        public Nullable<System.DateTime> trxdate { get; set; }
        public string description { get; set; }
        public Nullable<int> billmonth { get; set; }
        public Nullable<int> billyear { get; set; }
        public Nullable<int> typeid { get; set; }
        public string typename { get; set; }
        public int quantity { get; set; }
        public Nullable<decimal> unitprice { get; set; }
        public Nullable<decimal> extendedprice { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> printinvoice { get; set; }
        public Nullable<int> taxexempt { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<int> bppadmin { get; set; }
        public Nullable<int> credit { get; set; }
        public string creditnote { get; set; }
        public Nullable<int> creditinvoiceid { get; set; }
        public string invoiceflg { get; set; }
        public string invoicemsg { get; set; }
        public Nullable<int> postedby { get; set; }
        public Nullable<int> postedflg { get; set; }
        public Nullable<System.DateTime> posteddate { get; set; }
        public Nullable<int> invoicegenerated { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> detailserviceid { get; set; }
        public Nullable<int> separateinvoice { get; set; }
        public Nullable<int> batchid { get; set; }
        public Nullable<int> accountrebate { get; set; }
    }
}
