//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CustomerDetailFranchiseeDistribution
    {
        public int DistributionId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ContractDetailId { get; set; }
        public Nullable<int> DetailLineNumber { get; set; }
        public Nullable<int> FranchiseeId { get; set; }
        public string FranchiseeName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string FranchiseeNo { get; set; }
    }
}
