//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_C_Contact
    {
        public int id { get; set; }
        public int customerId { get; set; }
        public string fname { get; set; }
        public string mi { get; set; }
        public string lname { get; set; }
        public string title { get; set; }
        public string phone1 { get; set; }
        public string ext1 { get; set; }
        public string phone2 { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public int contactTypeId { get; set; }
        public int createdby { get; set; }
        public System.DateTime createdate { get; set; }
        public int modifiedby { get; set; }
        public System.DateTime modifieddate { get; set; }
        public string tmp_fullname { get; set; }
        public Nullable<int> tmp_impstatus { get; set; }
        public string tmp_impmsg { get; set; }
    }
}
