//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ContractDetailDestribution
    {
        public Nullable<int> LineNumber { get; set; }
        public string name { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int BillingFrequencyListId { get; set; }
        public string BillingFrequencyListName { get; set; }
        public Nullable<bool> Thur { get; set; }
        public Nullable<bool> Fri { get; set; }
        public Nullable<bool> Sat { get; set; }
        public Nullable<bool> Sun { get; set; }
        public Nullable<bool> Wed { get; set; }
        public Nullable<bool> Tues { get; set; }
        public Nullable<bool> Mon { get; set; }
        public Nullable<int> ContractId { get; set; }
        public int ContractDetailId { get; set; }
    }
}
