//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_C_BillSettings
    {
        public int id { get; set; }
        public int customerId { get; set; }
        public int status { get; set; }
        public int cpiincrease { get; set; }
        public int arstatus { get; set; }
        public Nullable<System.DateTime> effectivedate { get; set; }
        public int createinvoice { get; set; }
        public int ebill { get; set; }
        public int taxexempt { get; set; }
        public Nullable<int> taxauthorityid { get; set; }
        public int createdby { get; set; }
        public System.DateTime createdate { get; set; }
        public int modifiedby { get; set; }
        public System.DateTime modifieddate { get; set; }
        public Nullable<int> printinvoice { get; set; }
        public Nullable<int> printpastdue { get; set; }
        public string statusname { get; set; }
        public string arstatusname { get; set; }
        public string taxauthorityname { get; set; }
        public string invoicemessage { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<int> consolidatedinvoice { get; set; }
        public Nullable<int> invoicedate { get; set; }
        public string notes { get; set; }
    }
}
