//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_franchiserpt
    {
        public int id { get; set; }
        public Nullable<int> franid { get; set; }
        public Nullable<int> customertrxid { get; set; }
        public Nullable<int> frecurringid { get; set; }
        public Nullable<int> trxtypeid { get; set; }
        public string trxname { get; set; }
        public Nullable<System.DateTime> trxdate { get; set; }
        public Nullable<int> credit { get; set; }
        public Nullable<int> resell { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> unitprice { get; set; }
        public Nullable<decimal> extendedprice { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> trxtotal { get; set; }
        public Nullable<decimal> feeamount { get; set; }
        public string description { get; set; }
        public Nullable<int> paymentno { get; set; }
        public Nullable<int> billmonth { get; set; }
        public Nullable<int> billyear { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> balancetax { get; set; }
        public Nullable<decimal> totaldue { get; set; }
        public Nullable<int> appliedto { get; set; }
        public Nullable<int> chargedback { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> customerid { get; set; }
        public string vendorcode { get; set; }
        public string vendorinvoiceno { get; set; }
    }
}
