//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Fee
    {
        public int FeeId { get; set; }
        public string FeeName { get; set; }
        public int FeeRateTypeListId { get; set; }
        public string FeeRateTypeName { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
