//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_f_chargebackcreditfees
    {
        public string feename { get; set; }
        public int chargebackcreditid { get; set; }
        public int feeid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public int createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public int modifiedby { get; set; }
        public System.DateTime modifieddate { get; set; }
        public int Id { get; set; }
        public Nullable<int> allowEditDelete { get; set; }
        public int rate { get; set; }
        public int ratetype { get; set; }
        public string notes { get; set; }
    }
}
