//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_F_FranchiseeDetail
    {
        public int FranchiseeId { get; set; }
        public string FranchiseeNo { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateName { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Ext { get; set; }
        public string Fax { get; set; }
        public string Cell { get; set; }
        public string EmailAddress { get; set; }
        public string ContactName { get; set; }
        public string ContactType { get; set; }
        public string CPhone { get; set; }
        public string CExt { get; set; }
        public string CFax { get; set; }
        public string CCell { get; set; }
        public string CEmailAddress { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> BBPAdministrationFee { get; set; }
        public Nullable<bool> Chargeback { get; set; }
        public Nullable<bool> Incorporated { get; set; }
        public Nullable<bool> Print1099 { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<System.DateTime> DateSign { get; set; }
        public string StatusName { get; set; }
        public string PlanType { get; set; }
        public Nullable<System.DateTime> LastRenewedContractDate { get; set; }
    }
}
