//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_InvoiceContractDetailList
    {
        public int InvoiceId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int MasterTrxDetailId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public decimal TAXAmount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> MasterTrxId { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> ServiceTypeListId { get; set; }
    }
}
