//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_InvoiceDetail
    {
        public int InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Message { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string PurchaseOrderNo { get; set; }
        public string CustomerNo { get; set; }
        public string Customer { get; set; }
        public Nullable<int> AddressId_SoldTo { get; set; }
        public Nullable<int> AddressId_For { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string B_Name { get; set; }
        public string B_Attention { get; set; }
        public string B_Address1 { get; set; }
        public string B_Address2 { get; set; }
        public string B_City { get; set; }
        public string B_State { get; set; }
        public string B_PostalCode { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Phone { get; set; }
        public string B_Phone { get; set; }
        public Nullable<int> BillMonth { get; set; }
        public Nullable<int> BillYear { get; set; }
        public string EmailAddress { get; set; }
        public string InvoiceMessage { get; set; }
    }
}
