//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invoice
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string postalcode { get; set; }
        public string description { get; set; }
        public Nullable<decimal> hsubamt { get; set; }
        public Nullable<decimal> htaxamt { get; set; }
        public Nullable<decimal> htotalamt { get; set; }
        public string invoiceno { get; set; }
        public Nullable<System.DateTime> invoicedate { get; set; }
        public string detaildescription { get; set; }
        public int quantity { get; set; }
        public Nullable<decimal> itemamt { get; set; }
        public Nullable<decimal> subamt { get; set; }
        public Nullable<decimal> taxamt { get; set; }
        public Nullable<decimal> totalamt { get; set; }
    }
}
