//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MasterTrasactionList
    {
        public int MasterTrxId { get; set; }
        public Nullable<int> TransactionTypeId { get; set; }
        public string TransactionTypeName { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionNumber { get; set; }
        public string TransactionDescription { get; set; }
        public Nullable<int> RefId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> AmountTypeListId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TypeListId { get; set; }
        public string TypeListName { get; set; }
        public Nullable<int> LedgerAcctId { get; set; }
        public string LedgerAcctNumber { get; set; }
        public string LedgerAcctName { get; set; }
        public Nullable<int> LedgerSubAcctId { get; set; }
        public string LedgerSubAcctNumber { get; set; }
        public string LedgerSubAcctName { get; set; }
        public string Payee_Payer { get; set; }
    }
}
