//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_sys_F_PlanTypes
    {
        public int id { get; set; }
        public int franId { get; set; }
        public string plantype { get; set; }
        public float businessamount { get; set; }
        public Nullable<float> fee { get; set; }
        public Nullable<float> paymentamount { get; set; }
        public int noofpayments { get; set; }
        public Nullable<float> downpayment { get; set; }
        public Nullable<System.DateTime> obligationbegin { get; set; }
        public Nullable<System.DateTime> obligationend { get; set; }
        public Nullable<int> status { get; set; }
        public int createdby { get; set; }
        public System.DateTime createdate { get; set; }
        public string tmp_franno { get; set; }
        public string tmp_status { get; set; }
    }
}
