//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApi.Data.MasterDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class appSysCPI
    {
        public int id { get; set; }
        public int billmonth { get; set; }
        public int billyear { get; set; }
        public decimal percent { get; set; }
        public string description { get; set; }
        public Nullable<int> applied { get; set; }
        public int createdby { get; set; }
        public System.DateTime createdate { get; set; }
        public int modifiedby { get; set; }
        public System.DateTime modifieddate { get; set; }
    }
}
