//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JKCRMResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JKCRMResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JK.Resources.JKCRMResource", typeof(JKCRMResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accu Data.
        /// </summary>
        public static string accudata {
            get {
                return ResourceManager.GetString("accudata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act!.
        /// </summary>
        public static string act {
            get {
                return ResourceManager.GetString("act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string activities {
            get {
                return ResourceManager.GetString("activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lead.
        /// </summary>
        public static string addlead {
            get {
                return ResourceManager.GetString("addlead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log New Activity.
        /// </summary>
        public static string addnewactivity {
            get {
                return ResourceManager.GetString("addnewactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Lead.
        /// </summary>
        public static string addnewlead {
            get {
                return ResourceManager.GetString("addnewlead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string address1 {
            get {
                return ResourceManager.GetString("address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string address2 {
            get {
                return ResourceManager.GetString("address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahla Directory.
        /// </summary>
        public static string ahladirectory {
            get {
                return ResourceManager.GetString("ahladirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string am {
            get {
                return ResourceManager.GetString("am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string assignee {
            get {
                return ResourceManager.GetString("assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To.
        /// </summary>
        public static string assignto {
            get {
                return ResourceManager.GetString("assignto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaiatech PPC.
        /// </summary>
        public static string avaiatechppc {
            get {
                return ResourceManager.GetString("avaiatechppc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Time.
        /// </summary>
        public static string besttime {
            get {
                return ResourceManager.GetString("besttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biz List.
        /// </summary>
        public static string bizlist {
            get {
                return ResourceManager.GetString("bizlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string budget {
            get {
                return ResourceManager.GetString("budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Joural Bk of Lists.
        /// </summary>
        public static string businessjournalbkoflists {
            get {
                return ResourceManager.GetString("businessjournalbkoflists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string busy {
            get {
                return ResourceManager.GetString("busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string call {
            get {
                return ResourceManager.GetString("call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback.
        /// </summary>
        public static string callback {
            get {
                return ResourceManager.GetString("callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call In.
        /// </summary>
        public static string callin {
            get {
                return ResourceManager.GetString("callin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call.
        /// </summary>
        public static string coldcall {
            get {
                return ResourceManager.GetString("coldcall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Info.
        /// </summary>
        public static string companyinfo {
            get {
                return ResourceManager.GetString("companyinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string connected {
            get {
                return ResourceManager.GetString("connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        public static string corporate {
            get {
                return ResourceManager.GetString("corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string county {
            get {
                return ResourceManager.GetString("county", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criss Cross.
        /// </summary>
        public static string crisscross {
            get {
                return ResourceManager.GetString("crisscross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Provider.
        /// </summary>
        public static string currentprovider {
            get {
                return ResourceManager.GetString("currentprovider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string dateandtime {
            get {
                return ResourceManager.GetString("dateandtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dunn and Brad Street.
        /// </summary>
        public static string dunnandbradstreet {
            get {
                return ResourceManager.GetString("dunnandbradstreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string excel {
            get {
                return ResourceManager.GetString("excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franchise.
        /// </summary>
        public static string franchise {
            get {
                return ResourceManager.GetString("franchise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franchise Accounting.
        /// </summary>
        public static string franchiseaccounting {
            get {
                return ResourceManager.GetString("franchiseaccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoldMine.
        /// </summary>
        public static string goldmine {
            get {
                return ResourceManager.GetString("goldmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Leads.
        /// </summary>
        public static string goleadscom {
            get {
                return ResourceManager.GetString("goleadscom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haines.
        /// </summary>
        public static string haines {
            get {
                return ResourceManager.GetString("haines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoovers.
        /// </summary>
        public static string hoovers {
            get {
                return ResourceManager.GetString("hoovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported.
        /// </summary>
        public static string imported {
            get {
                return ResourceManager.GetString("imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Customer.
        /// </summary>
        public static string inactivecustomer {
            get {
                return ResourceManager.GetString("inactivecustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Customers.
        /// </summary>
        public static string inactivecustomers {
            get {
                return ResourceManager.GetString("inactivecustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string industry {
            get {
                return ResourceManager.GetString("industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info USA.
        /// </summary>
        public static string infousa {
            get {
                return ResourceManager.GetString("infousa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In House.
        /// </summary>
        public static string inhouse {
            get {
                return ResourceManager.GetString("inhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside Prospects.
        /// </summary>
        public static string insideprospects {
            get {
                return ResourceManager.GetString("insideprospects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JaniKing Vehicle.
        /// </summary>
        public static string janikingvehicle {
            get {
                return ResourceManager.GetString("janikingvehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junk Lead.
        /// </summary>
        public static string junklead {
            get {
                return ResourceManager.GetString("junklead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        public static string lead {
            get {
                return ResourceManager.GetString("lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead List Service.
        /// </summary>
        public static string leadlistservice {
            get {
                return ResourceManager.GetString("leadlistservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call or Setup Meeting.
        /// </summary>
        public static string leadneedstocallorsetupmeeting {
            get {
                return ResourceManager.GetString("leadneedstocallorsetupmeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Source.
        /// </summary>
        public static string leadsource {
            get {
                return ResourceManager.GetString("leadsource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string leadstatus {
            get {
                return ResourceManager.GetString("leadstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Voice Mail.
        /// </summary>
        public static string leftvoicemail {
            get {
                return ResourceManager.GetString("leftvoicemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Chamber.
        /// </summary>
        public static string localchamber {
            get {
                return ResourceManager.GetString("localchamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Locations.
        /// </summary>
        public static string locations {
            get {
                return ResourceManager.GetString("locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        public static string meeting {
            get {
                return ResourceManager.GetString("meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.I..
        /// </summary>
        public static string middleinitial {
            get {
                return ResourceManager.GetString("middleinitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Follow Up.
        /// </summary>
        public static string needsfollowup {
            get {
                return ResourceManager.GetString("needsfollowup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Requote.
        /// </summary>
        public static string needsrequote {
            get {
                return ResourceManager.GetString("needsrequote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiation.
        /// </summary>
        public static string negotation {
            get {
                return ResourceManager.GetString("negotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiation.
        /// </summary>
        public static string negotiation {
            get {
                return ResourceManager.GetString("negotiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer.
        /// </summary>
        public static string newcustomer {
            get {
                return ResourceManager.GetString("newcustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Lead.
        /// </summary>
        public static string newlead {
            get {
                return ResourceManager.GetString("newlead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Potential.
        /// </summary>
        public static string newpotential {
            get {
                return ResourceManager.GetString("newpotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Answer.
        /// </summary>
        public static string noanswer {
            get {
                return ResourceManager.GetString("noanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string outcome {
            get {
                return ResourceManager.GetString("outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Source.
        /// </summary>
        public static string outsource {
            get {
                return ResourceManager.GetString("outsource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string pdf {
            get {
                return ResourceManager.GetString("pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        public static string pm {
            get {
                return ResourceManager.GetString("pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential.
        /// </summary>
        public static string potential {
            get {
                return ResourceManager.GetString("potential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string provider {
            get {
                return ResourceManager.GetString("provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualified Lead.
        /// </summary>
        public static string qualifiedlead {
            get {
                return ResourceManager.GetString("qualifiedlead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Accepted.
        /// </summary>
        public static string quotationaccepted {
            get {
                return ResourceManager.GetString("quotationaccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Not Accepted.
        /// </summary>
        public static string quotationnotaccepted {
            get {
                return ResourceManager.GetString("quotationnotaccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Sent.
        /// </summary>
        public static string quotationsent {
            get {
                return ResourceManager.GetString("quotationsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready For Quotation.
        /// </summary>
        public static string readyforquotation {
            get {
                return ResourceManager.GetString("readyforquotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral.
        /// </summary>
        public static string referral {
            get {
                return ResourceManager.GetString("referral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Office.
        /// </summary>
        public static string regionaloffice {
            get {
                return ResourceManager.GetString("regionaloffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter.
        /// </summary>
        public static string reporter {
            get {
                return ResourceManager.GetString("reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string restaurant {
            get {
                return ResourceManager.GetString("restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail.
        /// </summary>
        public static string retail {
            get {
                return ResourceManager.GetString("retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirement Center.
        /// </summary>
        public static string retirementcenter {
            get {
                return ResourceManager.GetString("retirementcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Genie.
        /// </summary>
        public static string salegenie {
            get {
                return ResourceManager.GetString("salegenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string schedules {
            get {
                return ResourceManager.GetString("schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School K Thru 12.
        /// </summary>
        public static string schoolk12 {
            get {
                return ResourceManager.GetString("schoolk12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Center.
        /// </summary>
        public static string shoppingcenter {
            get {
                return ResourceManager.GetString("shoppingcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Room.
        /// </summary>
        public static string showroom {
            get {
                return ResourceManager.GetString("showroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skating Rink.
        /// </summary>
        public static string skatingrink {
            get {
                return ResourceManager.GetString("skatingrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorkins.
        /// </summary>
        public static string sorkins {
            get {
                return ResourceManager.GetString("sorkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spa.
        /// </summary>
        public static string spa {
            get {
                return ResourceManager.GetString("spa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports Stadium.
        /// </summary>
        public static string sportsstadium {
            get {
                return ResourceManager.GetString("sportsstadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadium Events Other.
        /// </summary>
        public static string stadiumeventsother {
            get {
                return ResourceManager.GetString("stadiumeventsother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Unit.
        /// </summary>
        public static string storageunit {
            get {
                return ResourceManager.GetString("storageunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery .
        /// </summary>
        public static string surgery {
            get {
                return ResourceManager.GetString("surgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string technology {
            get {
                return ResourceManager.GetString("technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemarketing.
        /// </summary>
        public static string telemarketing {
            get {
                return ResourceManager.GetString("telemarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Company.
        /// </summary>
        public static string telephonecompany {
            get {
                return ResourceManager.GetString("telephonecompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theater Arts.
        /// </summary>
        public static string theaterarts {
            get {
                return ResourceManager.GetString("theaterarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Share.
        /// </summary>
        public static string timeshare {
            get {
                return ResourceManager.GetString("timeshare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Centers.
        /// </summary>
        public static string trainingcenters {
            get {
                return ResourceManager.GetString("trainingcenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Co..
        /// </summary>
        public static string transportationco {
            get {
                return ResourceManager.GetString("transportationco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string university {
            get {
                return ResourceManager.GetString("university", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unqualified Lead.
        /// </summary>
        public static string unqualifiedlead {
            get {
                return ResourceManager.GetString("unqualifiedlead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Number.
        /// </summary>
        public static string wrongnumber {
            get {
                return ResourceManager.GetString("wrongnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Pages.
        /// </summary>
        public static string yellowpages {
            get {
                return ResourceManager.GetString("yellowpages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode.
        /// </summary>
        public static string zipCode {
            get {
                return ResourceManager.GetString("zipCode", resourceCulture);
            }
        }
    }
}
