//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebConfigResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebConfigResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JK.Resources.WebConfigResource", typeof(WebConfigResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3600.
        /// </summary>
        public static string CacheExpiresIn_seconds {
            get {
                return ResourceManager.GetString("CacheExpiresIn_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string emailFrom {
            get {
                return ResourceManager.GetString("emailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string emailHost {
            get {
                return ResourceManager.GetString("emailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string emailpassword {
            get {
                return ResourceManager.GetString("emailpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string emailPort {
            get {
                return ResourceManager.GetString("emailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        public static string emailsmtpClientTimeOut {
            get {
                return ResourceManager.GetString("emailsmtpClientTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string emailUseDefaultCredentials {
            get {
                return ResourceManager.GetString("emailUseDefaultCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string emailUserName {
            get {
                return ResourceManager.GetString("emailUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 699261585FAA8AA8.
        /// </summary>
        public static string EncKey {
            get {
                return ResourceManager.GetString("EncKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string ListPageSize {
            get {
                return ResourceManager.GetString("ListPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy hh:mm:ss.fffff tt.
        /// </summary>
        public static string LoggingDateFormate {
            get {
                return ResourceManager.GetString("LoggingDateFormate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string LoggingDebug {
            get {
                return ResourceManager.GetString("LoggingDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string LoggingError {
            get {
                return ResourceManager.GetString("LoggingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string LoggingException {
            get {
                return ResourceManager.GetString("LoggingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string LoggingInfo {
            get {
                return ResourceManager.GetString("LoggingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string RememberMeExpireIn_Days {
            get {
                return ResourceManager.GetString("RememberMeExpireIn_Days", resourceCulture);
            }
        }
    }
}
